apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ironic_port_exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipmi-sd
      type: service-discovery
  template:
    metadata:
      labels:
        app: ipmi-sd
        type: service-discovery
    spec:
      containers:
      - name: ipmi-sd
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.image }}:{{ .Values.tag }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 1
          failureThreshold: 3
        env:
        - name: LOGLEVEL
          value: "{{ .Values.log_level }}"
        - name: OS_VERSION
          value: "{{ .Values.tag }}"
        - name: OS_IRONIC_USERNAME
          value: "{{ .Values.global.ipmi_exporter_user }}"
        - name: OS_IRONIC_PASSWORD
          value: "{{ .Values.global.ipmi_exporter_user_passwd }}"
        - name: OS_USER_DOMAIN_NAME
          value: "{{ .Values.os_user_domain_name }}"
        - name: OS_PROJECT_NAME
          value: "{{ .Values.os_project_name }}"
        - name: OS_PROJECT_DOMAIN_NAME
          value: "{{ .Values.os_project_domain_name }}"